### ISSUE TITLE
Holding page needed.

### ISSUE THREAD

**Issue by OwainWilliams** [H5YR/H5YR#5]
I'm looking for creative people / person to come up with a nice looking holding page for the H5YR.com website. 

Can you help?

**Comment by LewSlade** [comment]
Hi Owain,

Here's a few questions just to get us moving. 

What is the purpose of this holding page?
- Just a placeholder for now or something more, data capture, overview of the future of H5YR?

Is there any existing branding material for H5YR? 
- Logo, colours, fonts, images.
- If no, does it need to tie into the Umbraco or Codegarden branding for example?

Stylewise are there any examples you could supply in terms of UI style that would be prefered?

Has there been any previous thought on the content of this holding page?
- I.e. images, copy, animated images, interaction? 

Is there a preference on the type of design files to be supplied for build? 
- I can produce the design in Adobe’s PSD or XD (preferably XD) and be handed over via XD’s private design spec link. Currently don’t have Sketch at home but could look into acquiring it as it is on my list to invest in for personal use. 

Initially, something really simple could work in the form of a short message about H5YR and a little animated image so there’s some life on the page. 

Cheers,
Lew.

**Comment by OwainWilliams** [comment]
What is the purpose of this holding page?

**Just a placeholder for now or something more, data capture, overview of the future of H5YR?**

Initially, just a page that will pull all the tweets that use the hashtag #h5yr and a bit of info about the project. 

**Is there any existing branding material for H5YR?**

Logo, colours, fonts, images.
If no, does it need to tie into the Umbraco or Codegarden branding for example?
Stylewise are there any examples you could supply in terms of UI style that would be prefered?

We have no image, colours or fonts. You have all the freedom in the world for this. It's not to tie in with Umbraco or Codegarden, this is a totally separate project. The only thing that ties this project in with Umbraco is the fact that the Umbraco community use the hashtag. The plan is to make this open to all, not just the Umbraco community.

**Has there been any previous thought on the content of this holding page?**

As mentioned above, just a short intro to what the project is and then the twitter feed of all h5yr tweets. 

**Is there a preference on the type of design files to be supplied for build?**

> I can produce the design in Adobe’s PSD or XD (preferably XD) and be handed over via XD’s private design spec link. Currently don’t have Sketch at home but could look into acquiring it as it is on my list to invest in for personal use.
> Initially, something really simple could work in the form of a short message about H5YR and a little animated image so there’s some life on the page.
> 

That all sounds fine. As for what format to use, I'll see if anyone with some frontend skills has any preference. I use Affinity Designer which handles PSD and AI.

**Comment by greystate** [comment]
I do fronted using Avocode, which is able to take PSD, Sketch and Adobe XD files to name a few, so XD would be fine by me :+1:

**Comment by LewSlade** [comment]
@greystate Awesome, I'll do this holding page design in XD but will probably invest in Sketch for future visuals.

@OwainWilliams I've created an InVision project which contains a wireframe of a page layout and structure. I've also added a few sketches showing a few ideas for potential graphic treatments: https://invis.io/ESPXBNRU9Z2

Keeping it simple before getting into the feed with a graphic based around the H5YR text. Thinking a typographic treatment with illustrated graphics to support. Potentially could animate it depending on the complexity. I can look into this or if its easier to code in the front end but can discuss this at a later date.

Brief message to users about the site followed by the twitter feed in a masonry layout. 

What are you thoughts on the layout and sketches?

**Comment by sumeshkp18** [comment]
@LewSlade The design looks good. I have added a #h5yr Usage number Ticker suggestion in the issues - #17  and comment on the Invision file. Please have a look and we can include the idea is good :) 

- Sumesh

**Comment by OwainWilliams** [comment]
Hi @LewSlade 
Great start and I'm liking the layout with all the tweets on the homepage. 
I think the only feedback I have about the logo / image is how will it look on for profile pics e.g. twitter account? Will it be clear what it is? 

I guess we could have two options, one is the larger and one is smaller and simplified for twitter / stickers (everyone loves a sticker). 

O.

**Comment by LewSlade** [comment]
@OwainWilliams It would be like you said, the image that i see sitting at the top of the page wouldn't be the logo. I've had a few ideas for a potential logo thats a lot simpler and would work better for profile pictures etc. Placed either top left or int he middle where the #H5YR text is.

I'll produce some sketches of a logo idea and add them to that invision page over the weekend (or lunch if i get chance to)

**Comment by Matthew-Wise** [comment]
I think we can safely close this one seen as we are beyond a holding page :) 

Thanks to all those who helped
