### ISSUE TITLE
Twitter feed on main site

### ISSUE THREAD

**Issue by OwainWilliams** [H5YR/H5YR#9]
We need a way to pull in all tweets that mention #h5yr or #h5is

On the old site, it used uTwit and I'm currently investigating getting this working on the website however, I'm also open to new ideas.

**Comment by NikRimington** [comment]
So, following on from what was being discussed on Slack, I think Skybrud.Social is a good option for this. One advantage is that it means we can style tweets however we like. (I don't know anything about uTwit so can't comment on if that is possible with that or not).

My other thought was we don't want the site hitting the twitter API every time the page/site is loaded so it might be worth looking at using something like HangFire to run a scheduled update check against the Twitter API. This can then update a local cache of tweets, either saved in the db or just straight into in memory cache.

Following on from this, we could utilise SignalR, and a front end templating framework such as react/angular/Knockout to update the view client side when new tweets are found to save visitors from refreshing the page.

Just some thoughts on usability for discussion :-)

**Comment by OwainWilliams** [comment]
Love these ideas!

**Comment by abjerner** [comment]
I don't think Matt is maintaining uTwit anymore, so Skybrud.Social seems like the way to go 😄 🍍 

Searching for a specific hashtag would be something like shown on this page:
https://social.skybrud.dk/twitter/endpoints/search/query-based-search/

If I remember correctly, a query could be `#h5yr OR #h5is` to search for both tags at the same time, but search for each tag individually could of course also work.

**Comment by Matthew-Wise** [comment]
With SignalR you could get it to play the you rock clip on update (with the option to turn that off)

**Comment by OwainWilliams** [comment]
So we have the twitter wall created now, we just need to cache the tweets and look at adding them in to examine so we can do some counting and maybe even searching.
